Repository TrueCar/gluestick, pull requests merged in 2018-04, with the labels that each got.

#1172 Add semver dependency for #1167
  packages/gluestick-cli/package-lock.json
  packages/gluestick-cli/package.json
  yarn.lock
Labels: CLA Signed

#1171 Move static imports to middleware.js and set up test mocks.
  package.json
  packages/gluestick/src/__tests__/mocks/EntryWrapper.js
  packages/gluestick/src/__tests__/mocks/applicationConfig.js
  packages/gluestick/src/__tests__/mocks/gluestickHooks.js
  packages/gluestick/src/__tests__/mocks/projectEntries.js
  packages/gluestick/src/__tests__/mocks/projectEntriesConfig.js
  packages/gluestick/src/__tests__/mocks/reduxMiddlewares.js
  packages/gluestick/src/renderer/__tests__/middleware.test.js
  packages/gluestick/src/renderer/main.js
  packages/gluestick/src/renderer/middleware.js
Labels: CLA Not Signed

#1168 Apply patches to properly load bunyan config file
  packages/gluestick-plugin-bunyan/src/__tests__/server.test.js
  packages/gluestick-plugin-bunyan/src/server.js
  packages/gluestick/src/plugins/prepareServerPlugins.js
Labels: CLA Signed

#1174 Fix bunyan logging options
  packages/gluestick-plugin-bunyan/package.json
  packages/gluestick-plugin-bunyan/src/__tests__/server.test.js
  packages/gluestick-plugin-bunyan/src/server.js
  yarn.lock
Labels: CLA Signed

#1173 Change logger to be a singleton and move to imports rather than DI.
  packages/gluestick/src/__tests__/logger.test.js
  packages/gluestick/src/config.js
  packages/gluestick/src/logger.js
  packages/gluestick/src/plugins/__tests__/serverPlugins.test.js
  packages/gluestick/src/plugins/serverPlugins.js
  packages/gluestick/src/renderer/__tests__/entry.test.js
  packages/gluestick/src/renderer/__tests__/middleware.test.js
  packages/gluestick/src/renderer/entry.js
  packages/gluestick/src/renderer/helpers/getRequirementsFromEntry.js
  packages/gluestick/src/renderer/helpers/hooks.js
  packages/gluestick/src/renderer/helpers/readAssets.js
  packages/gluestick/src/renderer/main.js
  packages/gluestick/src/renderer/middleware.js
Labels: CLA Not Signed

#1176 Create Webpack Bundle Analyzer Guide
  README.md
  docs/guides/WebpackBundleAnalyzerGuide.md
  docs/guides/img/webpack.gif
Labels: CLA Not Signed

#1181 LO-4520 Remove all npm lock files and ignore.
  .gitignore
  packages/gluestick-cli/package-lock.json
  packages/gluestick-env-expose-ast/package-lock.json
  packages/gluestick-generators/package-lock.json
  packages/gluestick-plugin-aphrodite/package-lock.json
  packages/gluestick-plugin-bunyan/package-lock.json
  packages/gluestick-plugin-eslint/package-lock.json
  packages/gluestick-plugin-no-fouc/package-lock.json
  packages/gluestick-plugin-radium/package-lock.json
  packages/gluestick/package-lock.json
  packages/gluestick/package.json
  yarn.lock
Labels: CLA Not Signed

#1183 Fix autoupgrade error
  packages/gluestick/src/config/defaults/glueStickConfig.js
Labels: CLA Signed

#1180 Refactor out universal-webpack.
  docs/configuration/Plugins.md
  packages/gluestick/package.json
  packages/gluestick/src/commands/start-client.js
  packages/gluestick/src/config/compileWebpackConfig.js
  packages/gluestick/src/config/webpack/webpack.config.js
  packages/gluestick/src/config/webpack/webpack.config.server.js
  packages/gluestick/src/renderer/helpers/linkAssets.js
  yarn.lock
Labels: CLA Not Signed, CLA Signed

#1187 Write to both project and gluestick build folders with watch.
  packages/gluestick-cli/src/watch.js
Labels: CLA Not Signed
